### ISSUE TITLE
Unable to extract historical data on certain stocks

### ISSUE THREAD

**Issue by tokeneve** [mlouielu/twstock#20]
I was unable to extract data for the following stocks. Just taking a random guess that it could be the reason ? ..  Attaching the date for 停止交易 for your reference. 

2311　日月光 2016/5/26
2317　鴻海 2016/3/30
1101　台泥/ 2017/4/19
1216　統一/ 2017/7/27
2354　鴻準 2016/3/30
2454　聯發科 2016/5/13
2912　統一超 2017/7/27

**Comment by mlouielu** [comment]
If you do like this, would you get the same result?

```
>>> import twstock
>>> s = twstock.Stock('2311')
>>> s.fetch_from(2016, 5)
Traceback (most recent call last):                         
  File "<stdin>", line 1, in <module>                      
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 144, in fetch_from                        
    self.raw_data.append(self.fetcher.fetch(year, month, self.sid))                                                    
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 56, in fetch                              
    data['data'] = self.purify(data)                       
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 74, in purify                             
    return [self._make_datatuple(d) for d in original_data['data']]                                                    
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 74, in <listcomp>                         
    return [self._make_datatuple(d) for d in original_data['data']]                                                    
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 65, in _make_datatuple                    
    data[3] = float(data[3].replace(',', ''))              
ValueError: could not convert string to float: '--'        
```

**Comment by tokeneve** [comment]
Hi Louie,


Thanks so much for the prompt reply and sharing the valuable resources through Github.


Please find below for the error message for your reference:


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-0fc360f3a8fb> in <module>()
      1 import twstock
      2 s = twstock.Stock('2311')
----> 3 s.fetch_from(2016, 5)

C:\Users\token\AppData\Roaming\Python\Python36\site-packages\twstock\stock.py in fetch_from(self, year, month)
    142         today = datetime.datetime.today()
    143         for year, month in self._month_year_iter(month, year, today.month, today.year):
--> 144             self.raw_data.append(self.fetcher.fetch(year, month, self.sid))
    145             self.data.extend(self.raw_data[-1]['data'])
    146         return self.data

C:\Users\token\AppData\Roaming\Python\Python36\site-packages\twstock\stock.py in fetch(self, year, month, sid, retry)
     54
     55         if data['stat'] == 'OK':
---> 56             data['data'] = self.purify(data)
     57         else:
     58             data['data'] = []

C:\Users\token\AppData\Roaming\Python\Python36\site-packages\twstock\stock.py in purify(self, original_data)
     72
     73     def purify(self, original_data):
---> 74         return [self._make_datatuple(d) for d in original_data['data']]
     75
     76

C:\Users\token\AppData\Roaming\Python\Python36\site-packages\twstock\stock.py in <listcomp>(.0)
     72
     73     def purify(self, original_data):
---> 74         return [self._make_datatuple(d) for d in original_data['data']]
     75
     76

C:\Users\token\AppData\Roaming\Python\Python36\site-packages\twstock\stock.py in _make_datatuple(self, data)
     63         data[1] = int(data[1].replace(',', ''))
     64         data[2] = int(data[2].replace(',', ''))
---> 65         data[3] = float(data[3].replace(',', ''))
     66         data[4] = float(data[4].replace(',', ''))
     67         data[5] = float(data[5].replace(',', ''))

ValueError: could not convert string to float: '--'


Kindly let me know if I could assist you further. Please keep up the great work!

Best regards,


Paul

________________________________
寄件者: Louie Lu <notifications@github.com>
寄件日期: 2017年8月21日 上午 09:36:57
收件者: mlouielu/twstock
副本: bibobo666; Author
主旨: Re: [mlouielu/twstock] Unable to extract historical data on certain stocks (#20)


If you do like this, would you get the same result?

>>> import twstock
>>> s = twstock.Stock('2311')
>>> s.fetch_from(2016, 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 144, in fetch_from
    self.raw_data.append(self.fetcher.fetch(year, month, self.sid))
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 56, in fetch
    data['data'] = self.purify(data)
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 74, in purify
    return [self._make_datatuple(d) for d in original_data['data']]
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 74, in <listcomp>
    return [self._make_datatuple(d) for d in original_data['data']]
  File "/home/grd/.local/lib/python3.6/site-packages/twstock/stock.py", line 65, in _make_datatuple
    data[3] = float(data[3].replace(',', ''))
ValueError: could not convert string to float: '--'

**Comment by mlouielu** [comment]
Thanks for the report, it seems is a parsing problem, I'll take a fix these days.

**Comment by tokeneve** [comment]
Please feel to let me know anytime you need someone to test the code.


Best regards,

Paul

________________________________
寄件者: Louie Lu <notifications@github.com>
寄件日期: 2017年8月21日 下午 12:40:10
收件者: mlouielu/twstock
副本: bibobo666; Author
主旨: Re: [mlouielu/twstock] Unable to extract historical data on certain stocks (#20)


Thanks for the report, it seems is a parsing problem, I'll take a fix these days.

**Comment by otaku0929** [comment]
import twstock
data = twstock.Stock('1110')
------
Traceback (most recent call last):
  File "stock_bias10.py", line 96, in <module>
    print(pt())
  File "stock_bias10.py", line 80, in pt
    content = sb(res)
  File "stock_bias10.py", line 26, in sb
    stockh = twstock.Stock(keys[i])
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 123, in __init__
    self.fetch_31()
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 152, in fetch_31
    self.fetch_from(before.year, before.month)
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 144, in fetch_from

    self.raw_data.append(self.fetcher.fetch(year, month, self.sid))
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 56, in fetch
    data['data'] = self.purify(data)
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 74, in purify
    return [self._make_datatuple(d) for d in original_data['data']]
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 74, in <listcomp>
    return [self._make_datatuple(d) for d in original_data['data']]
  File "C:\Python36\lib\site-packages\twstock\stock.py", line 65, in _make_datat
uple
    data[3] = float(data[3].replace(',', ''))
ValueError: could not convert string to float: '--'
