### ISSUE TITLE
RUN出現問題？

### ISSUE THREAD

**Issue by ab15963qw** [mlouielu/twstock#75]
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 /Users/yangjunyu/PycharmProjects/untitled4/nre.py
Traceback (most recent call last):
  File "/Users/yangjunyu/PycharmProjects/untitled4/nre.py", line 1, in <module>
    import twstock
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/twstock/__init__.py", line 3, in <module>
    from twstock import stock
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/twstock/stock.py", line 22, in <module>
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/twstock/stock.py", line 18, in <module>
    from .codes import codes
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/twstock/codes/__init__.py", line 1, in <module>
    from .fetch import __update_codes
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/twstock/codes/fetch.py", line 14, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

**Comment by mlouielu** [comment]
Since twstock depend on lxml, you will need to install lxml first.

I assume you are using macOS, please do
```
python -m pip install --user lxml
```

**Comment by ab15963qw** [comment]
ok!
